"""Adicionando campo 'username' ao modelo Usuario

Revision ID: 0c795037e57d
Revises: 7740e597ab7b
Create Date: 2024-12-05 11:16:56.977407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c795037e57d'
down_revision: Union[str, None] = '7740e597ab7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Usuarios', sa.Column('email', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_Usuarios_email'), 'Usuarios', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Usuarios_email'), table_name='Usuarios')
    op.drop_column('Usuarios', 'email')
    # ### end Alembic commands ###
