"""Adiciona coluna idade

Revision ID: 50b3b9cae527
Revises: 
Create Date: 2024-12-03 10:08:45.509361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50b3b9cae527'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Alunos', sa.Column('idade', sa.Integer(), nullable=True))
    op.drop_column('Alunos', 'age')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Alunos', sa.Column('age', sa.INTEGER(), nullable=True))
    op.drop_column('Alunos', 'idade')
    # ### end Alembic commands ###
