"""Adiciona coluna nome da mae.

Revision ID: c7796422cec1
Revises: 50b3b9cae527
Create Date: 2024-12-03 10:28:37.407665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7796422cec1'
down_revision: Union[str, None] = '50b3b9cae527'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Alunos', sa.Column('nome_mae', sa.String(), nullable=True))
    op.create_index(op.f('ix_Alunos_nome_mae'), 'Alunos', ['nome_mae'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Alunos_nome_mae'), table_name='Alunos')
    op.drop_column('Alunos', 'nome_mae')
    # ### end Alembic commands ###
